import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Icon from '../components/atoms/Icon';
import Arrow from '../components/atoms/Arrow';
import Button from '../components/atoms/Button';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Button type='outline'>Generate</Button>
    </div>
  )
}
