import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Icon from '../components/atoms/Icon';
import Arrow from '../components/atoms/Arrow';
import Button from '../components/atoms/Button';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>
      <Button type='outline'>Generate</Button>
    </div>
  )
}
