import Head from 'next/head'
import Icon from '../components/atoms/Icon';
import Arrow from '../components/atoms/Arrow';
import Button from '../components/atoms/Button';
import Tab from '../components/atoms/Tab';
import MainNav from '../components/molecules/MainNav';
import AuthNav from '../components/molecules/AuthNav';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className="732:p-32 w-full max-w-7xl">
        <MainNav />
      </header>
    </div>
  )
}
